/**
 * GSTD Smart Contract Deployment — Testnet
 *
 * Deploys in dependency order, wires cross-contract permissions:
 *   1. GSTDJetton           (no deps)
 *   2. TreasuryGold         (needs owner)
 *   3. DAOVoting            (needs gstdJetton)
 *   4. SettlementMaster     (needs gstdJetton, treasury, protocolFee)
 *   5. AgentRegistry        (needs settlement)
 *
 * After deploy:
 *   - SettlementMaster is set as GSTDJetton.mintAuthority (one-time lock)
 *   - DAOVoting  is set as SettlementMaster.owner
 *   - DAOVoting  is set as TreasuryGold.owner
 *
 * Usage:
 *   cp .env.example .env          # fill in values
 *   npx ts-node scripts/deploy-testnet.ts
 */

import 'dotenv/config';
import * as path from 'path';
import * as fs from 'fs';
import { Address, beginCell, Cell, contractAddress, toNano, TonClient, WalletContractV4 } from '@ton/ton';
import { mnemonicToPrivateKey } from '@ton/crypto';

// ── TypeScript wrappers generated by Tact compiler ─────────────────────────
import { GSTDJetton }        from '../build/GSTDJetton/GSTDJetton_GSTDJetton';
import { SettlementMaster }  from '../build/SettlementMaster/SettlementMaster_SettlementMaster';
import { AgentRegistry }     from '../build/AgentRegistry/AgentRegistry_AgentRegistry';
import { DAOVoting }         from '../build/DAOVoting/DAOVoting_DAOVoting';
import { TreasuryGold }      from '../build/TreasuryGold/TreasuryGold_TreasuryGold';

// ── Config ──────────────────────────────────────────────────────────────────
const NETWORK        = process.env.TON_NETWORK || 'testnet';
const MNEMONIC       = process.env.DEPLOYER_MNEMONIC || '';
const ADMIN_WALLET   = process.env.ADMIN_WALLET || '';
const XAUT_JETTON    = process.env.XAUT_JETTON_MASTER || 'EQA1R_LuQCLHlMgOo1S4G7Y7W1cd0FrAkbA10Zq7rddKxi9k';

const ENDPOINTS: Record<string, string> = {
    mainnet: 'https://toncenter.com/api/v2/jsonRPC',
    testnet: 'https://testnet.toncenter.com/api/v2/jsonRPC',
};

function sleep(ms: number) { return new Promise(r => setTimeout(r, ms)); }

async function waitSeqno(wallet: any, seqno: number) {
    for (let i = 0; i < 40; i++) {
        await sleep(3000);
        const cur = await wallet.getSeqno();
        if (cur > seqno) return;
    }
    throw new Error('Tx not confirmed after 120s');
}

// ── Jetton metadata cell (TEP-64 on-chain format) ──────────────────────────
function buildMetadataCell(): Cell {
    const meta = beginCell()
        .storeUint(0, 8)              // on-chain snake format
        .storeStringTail(JSON.stringify({
            name:        'GSTD Token',
            description: 'AI Compute Network Governance & Utility Token',
            symbol:      'GSTD',
            decimals:    '9',
            image:       'https://app.gstdtoken.com/gstd-logo.png',
        }))
        .endCell();
    return meta;
}

async function main() {
    if (NETWORK !== 'testnet') {
        console.error('This script only deploys to testnet. Set TON_NETWORK=testnet.');
        process.exit(1);
    }
    if (!MNEMONIC)     { console.error('DEPLOYER_MNEMONIC not set'); process.exit(1); }
    if (!ADMIN_WALLET) { console.error('ADMIN_WALLET not set');      process.exit(1); }

    const adminAddr = Address.parse(ADMIN_WALLET);

    console.log('════════════════════════════════════════════════');
    console.log('  GSTD Contract Deployment — TESTNET');
    console.log(`  Admin: ${ADMIN_WALLET}`);
    console.log('════════════════════════════════════════════════\n');

    // ── Connect ────────────────────────────────────────────────────────────
    const client  = new TonClient({ endpoint: ENDPOINTS[NETWORK], apiKey: process.env.TON_API_KEY });
    const keyPair = await mnemonicToPrivateKey(MNEMONIC.split(' '));
    const wallet  = WalletContractV4.create({ publicKey: keyPair.publicKey, workchain: 0 });
    const provider = client.open(wallet);

    const deployer = wallet.address;
    console.log(`Deployer: ${deployer.toString()}`);
    const balance = await client.getBalance(deployer);
    console.log(`Balance: ${Number(balance) / 1e9} TON\n`);

    if (Number(balance) < toNano('3')) {
        console.error('Insufficient balance. Need ≥ 3 TON. Get testnet TON at https://t.me/testgiver_ton_bot');
        process.exit(1);
    }

    let seqno = await provider.getSeqno();
    const deployed: Record<string, string> = {};

    // ── 1. GSTDJetton ──────────────────────────────────────────────────────
    console.log('1️⃣  Deploying GSTDJetton...');
    const jettonInit = await GSTDJetton.init(adminAddr, buildMetadataCell());
    const jettonAddr = contractAddress(0, jettonInit);
    deployed.GSTDJetton = jettonAddr.toString();

    if (!(await client.isContractDeployed(jettonAddr))) {
        const jetton = client.open(new GSTDJetton(jettonAddr, jettonInit));
        await jetton.send(provider.sender(keyPair.secretKey), { value: toNano('0.5') }, {
            $$type: 'Deploy',
            queryId: BigInt(Date.now()),
        });
        await waitSeqno(provider, seqno++);
        console.log(`   ✅ GSTDJetton: ${jettonAddr.toString()}`);
    } else {
        console.log(`   ✓ Already deployed: ${jettonAddr.toString()}`);
    }

    // ── 2. TreasuryGold ────────────────────────────────────────────────────
    console.log('\n2️⃣  Deploying TreasuryGold...');
    // dexRouter: use zero address on testnet (STON.fi not active on testnet)
    const DEX_ROUTER = process.env.STONFI_ROUTER
        ? Address.parse(process.env.STONFI_ROUTER)
        : Address.parse('EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c');
    const treasuryInit = await TreasuryGold.init(adminAddr, Address.parse(XAUT_JETTON), DEX_ROUTER);
    const treasuryAddr = contractAddress(0, treasuryInit);
    deployed.TreasuryGold = treasuryAddr.toString();

    if (!(await client.isContractDeployed(treasuryAddr))) {
        const treasury = client.open(new TreasuryGold(treasuryAddr, treasuryInit));
        await treasury.send(provider.sender(keyPair.secretKey), { value: toNano('0.3') }, {
            $$type: 'Deploy',
            queryId: BigInt(Date.now()),
        });
        await waitSeqno(provider, seqno++);
        console.log(`   ✅ TreasuryGold: ${treasuryAddr.toString()}`);
    } else {
        console.log(`   ✓ Already deployed: ${treasuryAddr.toString()}`);
    }

    // ── 3. DAOVoting ───────────────────────────────────────────────────────
    console.log('\n3️⃣  Deploying DAOVoting...');
    const daoInit = await DAOVoting.init(adminAddr, jettonAddr);
    const daoAddr = contractAddress(0, daoInit);
    deployed.DAOVoting = daoAddr.toString();

    if (!(await client.isContractDeployed(daoAddr))) {
        const dao = client.open(new DAOVoting(daoAddr, daoInit));
        await dao.send(provider.sender(keyPair.secretKey), { value: toNano('0.3') }, {
            $$type: 'Deploy',
            queryId: BigInt(Date.now()),
        });
        await waitSeqno(provider, seqno++);
        console.log(`   ✅ DAOVoting: ${daoAddr.toString()}`);
    } else {
        console.log(`   ✓ Already deployed: ${daoAddr.toString()}`);
    }

    // ── 4. SettlementMaster ────────────────────────────────────────────────
    console.log('\n4️⃣  Deploying SettlementMaster...');
    // protocolFee wallet = admin wallet initially; swap to burn contract after deploy
    const settlementInit = await SettlementMaster.init(adminAddr, jettonAddr, treasuryAddr, adminAddr);
    const settlementAddr = contractAddress(0, settlementInit);
    deployed.SettlementMaster = settlementAddr.toString();

    if (!(await client.isContractDeployed(settlementAddr))) {
        const settlement = client.open(new SettlementMaster(settlementAddr, settlementInit));
        await settlement.send(provider.sender(keyPair.secretKey), { value: toNano('0.3') }, {
            $$type: 'Deploy',
            queryId: BigInt(Date.now()),
        });
        await waitSeqno(provider, seqno++);
        console.log(`   ✅ SettlementMaster: ${settlementAddr.toString()}`);
    } else {
        console.log(`   ✓ Already deployed: ${settlementAddr.toString()}`);
    }

    // ── 5. AgentRegistry ───────────────────────────────────────────────────
    console.log('\n5️⃣  Deploying AgentRegistry...');
    const registryInit = await AgentRegistry.init(adminAddr, settlementAddr);
    const registryAddr = contractAddress(0, registryInit);
    deployed.AgentRegistry = registryAddr.toString();

    if (!(await client.isContractDeployed(registryAddr))) {
        const registry = client.open(new AgentRegistry(registryAddr, registryInit));
        await registry.send(provider.sender(keyPair.secretKey), { value: toNano('0.3') }, {
            $$type: 'Deploy',
            queryId: BigInt(Date.now()),
        });
        await waitSeqno(provider, seqno++);
        console.log(`   ✅ AgentRegistry: ${registryAddr.toString()}`);
    } else {
        console.log(`   ✓ Already deployed: ${registryAddr.toString()}`);
    }

    // ── Cross-contract wiring ──────────────────────────────────────────────
    console.log('\n🔗 Wiring cross-contract permissions...');

    // 6a. Set SettlementMaster as GSTDJetton.mintAuthority (one-time, irreversible)
    console.log('   → SetMintAuthority: GSTDJetton ← SettlementMaster');
    const jetton = client.open(new GSTDJetton(jettonAddr));
    await jetton.send(provider.sender(keyPair.secretKey), { value: toNano('0.05') }, {
        $$type: 'SetMintAuthority',
        newAuthority: settlementAddr,
    });
    await waitSeqno(provider, seqno++);
    console.log('   ✅ Mint authority locked to SettlementMaster');

    // 6b. Set gateway on SettlementMaster
    console.log('   → SetGateway: SettlementMaster ← admin (update to actual gateway later)');
    const settlement = client.open(new SettlementMaster(settlementAddr));
    await settlement.send(provider.sender(keyPair.secretKey), { value: toNano('0.05') }, {
        $$type: 'SetGateway',
        gateway: adminAddr,  // replace with actual gateway after deploying gstdbot on-chain
    });
    await waitSeqno(provider, seqno++);
    console.log('   ✅ Gateway set');

    // ── Save deployment record ─────────────────────────────────────────────
    const record = {
        network: NETWORK,
        deployedAt: new Date().toISOString(),
        deployer: deployer.toString(),
        admin: ADMIN_WALLET,
        contracts: deployed,
        pendingActions: [
            'Transfer ownership of SettlementMaster to DAOVoting when DAO is ready',
            'Transfer ownership of TreasuryGold to DAOVoting when DAO is ready',
            'Update SettlementMaster.gateway to actual orchestrator address',
            'Update SettlementMaster.protocolFee to buyback contract when deployed',
        ],
    };

    const outPath = path.join(__dirname, '..', `deployment-${NETWORK}.json`);
    fs.writeFileSync(outPath, JSON.stringify(record, null, 2));

    console.log('\n════════════════════════════════════════════════');
    console.log('  DEPLOYMENT COMPLETE');
    console.log('════════════════════════════════════════════════');
    for (const [name, addr] of Object.entries(deployed)) {
        console.log(`  ${name.padEnd(20)}: ${addr}`);
    }
    console.log(`\n📄 Saved to: ${outPath}`);
    console.log('\n⚠️  Next steps:');
    console.log('  1. Verify contracts on https://testnet.tonscan.org');
    console.log('  2. Set these addresses in Vercel env vars:');
    console.log(`     NEXT_PUBLIC_TON_JETTON=${deployed.GSTDJetton}`);
    console.log(`     NEXT_PUBLIC_SETTLEMENT=${deployed.SettlementMaster}`);
    console.log(`     NEXT_PUBLIC_DAO=${deployed.DAOVoting}`);
    console.log(`     NEXT_PUBLIC_REGISTRY=${deployed.AgentRegistry}`);
    console.log('  3. After testnet validation — run deploy-mainnet.ts');
}

main().catch(err => { console.error(err); process.exit(1); });
